using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.hiucko.Donate;

[GenerateTypedNameReferences]
public sealed partial class DonateWindow : FancyWindow
{
    public DonateWindow()
    {
        RobustXamlLoader.Load(this);
    }
}