- type: department
  parent: CMDepartmentBase
  id: CMEngineering
  name: department-CMEngineering
  description: cm-department-Engineering-description
  color: "#A66300"
  roles:
  - CMChiefEngineer
  - CMOrdnanceTech
  - CMMaintTech
  hidden: true # TODO RMC14
