- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconChiefEngineer
  icon:
    sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_ce

- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconOrdnanceTech
  icon:
    sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_ot

- type: jobIcon
  parent: CMJobIconBase
  id: CMJobIconMaintTech
  icon:
    sprite: /Textures/_RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_mt
